#ifndef MAIN_H
#define MAIN_H

#define VERSION "0.1.0"
#define CAMPSITE_COMPARE "campsite v0.1"
#define FILE_HEADER "nade01"
#define DB_HEADER "aoi01\n\n# this database is designed to be human readable,\n# but not human editable. please do not edit this file,\n# as it is automatically updated and created by shima.\n"

enum RetCode {
    SHM_SUCCESS,
    SHM_UNKNOWN_COMMAND,
    SHM_BAD_ARGS,
    SHM_INVALID_FILE,
    SHM_INVALID_CAMPSITE_VER,
    SHM_MALFORMED_CAMPSITE,
    SHM_PREPARE_CMD_ERROR,
    SHM_FILESYSTEM_ERROR,
    SHM_EXTRACT_ERROR,
    SHM_COMPRESS_ERROR,
    SHM_UNKNOWN_PACKAGE,
    SHM_BULK_BUILD_ERRORS,
    SHM_CORRUPT_DB
};

#endif