#ifndef MAIN_H
#define MAIN_H

#include <stdio.h>

#define VERSION "0.1.0"
#define CAMPSITE_COMPARE "campsite v0.1"
#define FILE_HEADER "nade01"
#define DB_HEADER "aoi01\n\n# this database is designed to be human readable,\n# but not human editable. please do not edit this file,\n# as it is automatically updated and created by shima.\n"
#define ROOT_DIR "/"

struct PkgArgInfo {
    char **local_packages;
    char **db_packages;
    size_t num_local;
    size_t num_db;
};

enum RetCode {
    SHM_SUCCESS,
    SHM_UNKNOWN_COMMAND,
    SHM_BAD_ARGS,
    SHM_INVALID_FILE,
    SHM_INVALID_CAMPSITE_VER,
    SHM_MALFORMED_CAMPSITE,
    SHM_PREPARE_CMD_ERROR,
    SHM_FILESYSTEM_ERROR,
    SHM_EXTRACT_ERROR,
    SHM_COMPRESS_ERROR,
    SHM_UNKNOWN_PACKAGE,
    SHM_BULK_BUILD_ERRORS,
    SHM_CORRUPT_DB,
    SHM_SERVER_ERROR
};

#endif